# Configuration principale BioCybe

system:
  name: BioCybe
  version: 0.1.0
  environment: development  # development, testing, production

modules:
  detection:
    enabled: true
    log_level: debug
  isolation:
    enabled: true
    log_level: info
  neutralization:
    enabled: true
    log_level: info
  learning:
    enabled: true
    log_level: info
  api:
    enabled: true
    log_level: info
  ui:
    enabled: true
    log_level: info

logging:
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/biocybe.log"
  max_size: 10  # MB
  backups: 5
  console_level: info
  file_level: debug

database:
  type: sqlite  # sqlite, postgresql, mysql
  path: "db/biocybe.db"  # Pour SQLite
  # Pour d'autres bases de données
  # host: localhost
  # port: 5432
  # name: biocybe
  # user: biocybe_user
  # password: "votre_mot_de_passe_sécurisé"

api:
  host: 0.0.0.0
  port: 8000
  debug: true
  auth_required: true
  rate_limiting: true
  max_requests: 100  # par minute
  timeout: 30  # secondes

ui:
  host: 0.0.0.0
  port: 8080
  theme: "light"  # light, dark
  dashboard_update_interval: 5  # secondes

threat_intelligence:
  sharing_enabled: true
  federated_learning: true
  anonymous_telemetry: true
  update_interval: 3600  # secondes

resources:
  max_cpu_usage: 50  # pourcentage
  max_memory_usage: 1024  # MB
  max_disk_usage: 5120  # MB
  sandbox_timeout: 300  # secondes
  
notifications:
  email:
    enabled: false
    smtp_server: "smtp.example.com"
    smtp_port: 587
    sender: "biocybe@example.com"
    recipients: ["admin@example.com"]
  webhook:
    enabled: false
    url: "https://example.com/webhook"
    events: ["critical_threat", "system_repair", "quarantine"]
  syslog:
    enabled: true
    facility: "local0"
    priority: "info"